{"DBCallId":"7b78baa5-fd10-4f03-843e-77f5f5408a4d","TimeStamp":"2024-12-16T14:47:44.5633674-03:00","Query":" SELECT DATA_MOV_ABERTO , CURRENT DATE FROM SEGUROS.SISTEMAS WHERE IDE_SISTEMA = 'VA'","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [58005] [IBM][DB2.NET] SQL0902 An unexpected exception has occurred in Process: 13156 Thread 17 AppDomain: Name:testhost There are no context policies. Function: DB2DataReader.Read() CallStack: at System.Environment.get_StackTrace() at IBM.Data.Db2.DB2ConnPool.HandleUnknownErrors(String strFncMsg, Exception exception, Boolean bThrow) at IBM.Data.Db2.DB2DataReader.Read() at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1201 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 737 at IA_ConverterCommons.QueryBasis`1.Open(Object procParams) in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\IA_ConverterCommons\\Basis\\QueryBasis.cs:line 234 at Sias.VidaAzul.DB2.VA0469B.R0100_00_SELECT_SISTEMAS_DB_SELECT_1_Query1.Execute(R0100_00_SELECT_SISTEMAS_DB_SELECT_1_Query1 r0100_00_SELECT_SISTEMAS_DB_SELECT_1_Query1) in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaAzul\\DB2\\VA0469B\\R0100_00_SELECT_SISTEMAS_DB_SELECT_1_Query1.cs:line 44 at Code.VA0469B.R0100_00_SELECT_SISTEMAS_DB_SELECT_1() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaAzul\\Code\\VA0469B.cs:line 1500 at FileTests.Test_DB.VA0469B_Tests_DB.VA0469B_Database() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\FileTests.Test\\FileTests.Test\\VA0469B_Tests_DB.cs:line 25 at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 151 at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 278 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__1() at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 243 at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 242 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestInvoker.cs:line 112 at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 207 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestInvoker`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 190 at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 84 at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 67 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestRunner`1.RunAsync() at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs:line 139 at Xunit.Sdk.TestCaseRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCaseRunner.cs:line 82 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCaseRunner`1.RunAsync() at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs:line 162 at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestMethodRunner.cs:line 45 at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 136 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() at Xunit.Sdk.TestMethodRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 106 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunAsync() at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs:line 199 at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at Xunit.Sdk.TestClassRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs:line 175 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunAsync() at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs:line 185 at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at Xunit.Sdk.TestCollectionRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs:line 101 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) at System.Threading.Tasks.Task.ExecuteEntry() at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s) at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 106 at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action) in /_/src/xunit.execution/Sdk/Utility/ExecutionContextHelper.cs:line 110 at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in /_/src/common/XunitWorkerThread.cs:line 37 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) InnerException Message: Invalid Handle Check InnerException property for more detail. SQLSTATE=58005"}
{"DBCallId":"133ddf77-c4f9-4bf3-bfd8-6651447306c4","TimeStamp":"2024-12-16T14:47:49.5771488-03:00","Query":"SELECT NUM_APOLICE , NUM_ENDOSSO , COD_SUBGRUPO , COD_USUARIO , COD_OPERACAO , NUM_CERTIFICADO , NUM_PARCELA , SIT_REGISTRO , NUM_ORDEM , QUANTIDADE , MES_REFERENCIA , ANO_REFERENCIA , ORGAO_EMISSOR , NUM_SINISTRO , NUM_COPIAS , DATA_SOLICITACAO , NUM_APOL_LIDER FROM SEGUROS.RELATORIOS WHERE COD_RELATORIO = 'VA0469B' AND SIT_REGISTRO = '0' ORDER BY NUM_APOLICE , COD_SUBGRUPO","sqlCode":999,"rowsCount":0,"Time":"1 ms","Error":">>> Erro: ERROR [58005] [IBM][DB2.NET] SQL0902 An unexpected exception has occurred in Process: 13156 Thread 17 AppDomain: Name:testhost There are no context policies. Function: DB2DataReader.Read() CallStack: at System.Environment.get_StackTrace() at IBM.Data.Db2.DB2ConnPool.HandleUnknownErrors(String strFncMsg, Exception exception, Boolean bThrow) at IBM.Data.Db2.DB2DataReader.Read() at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1201 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 737 at IA_ConverterCommons.QueryBasis`1.Open(Object procParams) in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\IA_ConverterCommons\\Basis\\QueryBasis.cs:line 234 at Sias.VidaAzul.DB2.VA0469B.VA0469B_TRELAT.Open() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaAzul\\DB2\\VA0469B\\VA0469B_TRELAT.cs:line 50 at Code.VA0469B.R0900_00_DECLARE_RELATORIOS_DB_OPEN_1() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaAzul\\Code\\VA0469B.cs:line 1625 at FileTests.Test_DB.VA0469B_Tests_DB.VA0469B_Database() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\FileTests.Test\\FileTests.Test\\VA0469B_Tests_DB.cs:line 26 at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 151 at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 278 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__1() at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 243 at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 242 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestInvoker.cs:line 112 at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 207 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestInvoker`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 190 at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 84 at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 67 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestRunner`1.RunAsync() at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs:line 139 at Xunit.Sdk.TestCaseRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCaseRunner.cs:line 82 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCaseRunner`1.RunAsync() at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs:line 162 at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestMethodRunner.cs:line 45 at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 136 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() at Xunit.Sdk.TestMethodRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 106 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunAsync() at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs:line 199 at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at Xunit.Sdk.TestClassRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs:line 175 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunAsync() at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs:line 185 at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at Xunit.Sdk.TestCollectionRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs:line 101 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) at System.Threading.Tasks.Task.ExecuteEntry() at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s) at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 106 at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action) in /_/src/xunit.execution/Sdk/Utility/ExecutionContextHelper.cs:line 110 at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in /_/src/common/XunitWorkerThread.cs:line 37 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) InnerException Message: Year, Month, and Day parameters describe an un-representable DateTime. Check InnerException property for more detail. SQLSTATE=58005"}
{"DBCallId":"6da6adae-8e07-436f-a07d-c2de5ea9742a","TimeStamp":"2024-12-16T14:47:51.6087341-03:00","Query":" SELECT NUM_CERTIFICADO FROM SEGUROS.HIST_LANC_CTA WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000' AND CODCONV = 6090 AND SIT_REGISTRO NOT IN ( ' ' , '1' , '2' ) FETCH FIRST 1 ROW ONLY WITH UR","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"062c46cf-6d79-4380-a9cd-4bb38375a242","TimeStamp":"2024-12-16T14:47:52.9081792-03:00","Query":" UPDATE SEGUROS.RELATORIOS SET SIT_REGISTRO = ' ' WHERE NUM_CERTIFICADO = '000000000000000' AND COD_RELATORIO = 'VA0469B' AND SIT_REGISTRO = '0' AND NUM_PARCELA = '0000'","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"c81b1c8b-a613-42bb-9ab3-a29cde6b3f59","TimeStamp":"2024-12-16T14:47:53.9425879-03:00","Query":" SELECT COD_FONTE , DATA_QUITACAO , SIT_REGISTRO , DTA_DECLINIO , COD_PRODUTO FROM SEGUROS.PROPOSTAS_VA WHERE NUM_CERTIFICADO = '000000000000000' WITH UR","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"3d72ff7b-21e6-426f-8b50-b330f3f6cc32","TimeStamp":"2024-12-16T14:47:54.6733582-03:00","Query":" SELECT NUM_TITULO , DATA_VENCIMENTO , SIT_REGISTRO , OCORR_HISTORICO , COD_DEVOLUCAO FROM SEGUROS.COBER_HIST_VIDAZUL WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"06555c01-560a-4704-9f72-20f5ab5e7ece","TimeStamp":"2024-12-16T14:47:55.3531726-03:00","Query":" SELECT VALUE(COUNT(*) ,0) FROM SEGUROS.HIST_LANC_CTA WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000' AND SIT_REGISTRO = '3'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"ba85c3d0-f665-4f85-aab5-b3b89d9d1359","TimeStamp":"2024-12-16T14:47:56.4750467-03:00","Query":" SELECT VALUE(MAX(OCORR_HISTORICOCTA) ,0) FROM SEGUROS.HIST_LANC_CTA WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000' AND SIT_REGISTRO = ' ' AND TIPLANC = '2' AND CODCONV = '0000' AND (NSAS IS NULL OR NSAS = 0)","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"a551b497-1e97-46e2-96d8-ed2b4039743a","TimeStamp":"2024-12-16T14:47:57.2208151-03:00","Query":" SELECT VALUE(PRM_TOTAL ,0) FROM SEGUROS.HIST_LANC_CTA WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000' AND TIPLANC = '2' AND CODCONV = 6090 AND SIT_REGISTRO NOT IN ( ' ' , '2' , '8' , 'A' ) WITH UR","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"ad6b341a-f6f8-494b-b9a0-202b0752de0b","TimeStamp":"2024-12-16T14:47:57.9430629-03:00","Query":" SELECT DATA_VENCIMENTO , PREMIO_VG , PREMIO_AP , OCORR_HISTORICO , PREMIO_VG + PREMIO_AP FROM SEGUROS.PARCELAS_VIDAZUL WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"04255b5a-27b2-447c-bbe5-80aeb375c85e","TimeStamp":"2024-12-16T14:47:59.6354918-03:00","Query":" SELECT OPCAOPAG FROM SEGUROS.PROPOSTA_FIDELIZ WHERE NUM_PROPOSTA_SIVPF = '000000000000000' WITH UR","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"24c8170e-2a93-4d9b-947a-3cc2dfc905eb","TimeStamp":"2024-12-16T14:48:04.6027874-03:00","Query":" SELECT OPCAO_PAGAMENTO , COD_AGENCIA_DEBITO , OPE_CONTA_DEBITO , NUM_CONTA_DEBITO , DIG_CONTA_DEBITO FROM SEGUROS.OPCAO_PAG_VIDAZUL WHERE NUM_CERTIFICADO = '000000000000000' AND DATA_TERVIGENCIA = '9999-12-31'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"27a462c6-4062-4b3c-a3a2-89e52c597072","TimeStamp":"2024-12-16T14:48:04.9286-03:00","Query":" UPDATE SEGUROS.COBER_HIST_VIDAZUL SET DATA_VENCIMENTO = '2024-12-10', PRM_TOTAL = '0000000000000.00', SIT_REGISTRO = '2', COD_OPERACAO = '0000', OCORR_HISTORICO = '0000', COD_DEVOLUCAO = '0000' WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000'","sqlCode":999,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"10e794c8-60fa-4eab-9548-18b723e3ed92","TimeStamp":"2024-12-16T14:48:05.3244946-03:00","Query":" SELECT COD_CO FROM SEGUROS.USU_FIL_SENHA WHERE CODUSU = ' ' AND NIVEL_AUTORIZACAO = 'S' AND TIPO_FUNCAO = 'DEVOLUCAO EM CHEQUE' AND SITUACAO = ' '","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"afa6b27c-d6ba-448d-8abb-e40e5be94d5b","TimeStamp":"2024-12-16T14:48:07.2376752-03:00","Query":" SELECT T1.NUM_CERTIFICADO , T1.COD_OPERACAO , T1.DATA_OPERACAO FROM SEGUROS.MOVIMENTO_VGAP T1 , SEGUROS.SEGURADOS_VGAP T2 WHERE T1.NUM_CERTIFICADO = '000000000000000' AND T1.COD_OPERACAO BETWEEN 0400 AND 0499 AND T1.NUM_CERTIFICADO = T2.NUM_CERTIFICADO AND NOT EXISTS ( SELECT T3.NUM_APOLICE , T3.NUM_ITEM FROM SEGUROS.SEGURADOSVGAP_HIST T3 WHERE T3.NUM_APOLICE = T2.NUM_APOLICE AND T3.NUM_ITEM = T2.NUM_ITEM AND T3.COD_OPERACAO BETWEEN 0500 AND 0599 AND T3.DATA_OPERACAO > T1.DATA_OPERACAO ) WITH UR","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"6d191738-cd3c-438b-b39e-ac9463b93486","TimeStamp":"2024-12-16T14:48:07.4332567-03:00","Query":" SELECT T1.NUM_CERTIFICADO , T1.COD_OPERACAO , T1.DATA_OPERACAO FROM SEGUROS.MOVIMENTO_VGAP T1 WHERE T1.NUM_CERTIFICADO = '000000000000000' AND T1.COD_OPERACAO BETWEEN 0400 AND 0499 AND NOT EXISTS ( SELECT T2.NUM_CERTIFICADO FROM SEGUROS.MOVIMENTO_VGAP T2 WHERE T2.NUM_CERTIFICADO = T1.NUM_CERTIFICADO AND T2.COD_OPERACAO BETWEEN 0500 AND 0599 AND T2.DATA_OPERACAO > T1.DATA_OPERACAO ) WITH UR","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"956596a5-3300-4d09-95b8-d25c4f8c94ad","TimeStamp":"2024-12-16T14:48:07.7485052-03:00","Query":" SELECT T1.NUM_CERTIFICADO , T1.COD_OPERACAO , T1.DATA_OPERACAO FROM SEGUROS.MOVIMENTO_VGAP T1 WHERE T1.NUM_CERTIFICADO = '000000000000000' AND T1.COD_OPERACAO BETWEEN 0400 AND 0499 ORDER BY T1.DATA_OPERACAO DESC FETCH FIRST 1 ROW ONLY WITH UR","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"b473975a-3e15-496c-8541-823d038221c8","TimeStamp":"2024-12-16T14:48:07.9038435-03:00","Query":" SELECT COD_NAOACEITE FROM SEGUROS.CONVENIOS_VG WHERE NUM_APOLICE = '0000000000000' AND CODSUBES = '0000'","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"165e1c15-c24e-4797-a0e7-a0035fab4702","TimeStamp":"2024-12-16T14:48:08.0726547-03:00","Query":" INSERT INTO SEGUROS.HIST_LANC_CTA (NUM_CERTIFICADO, NUM_PARCELA, OCORR_HISTORICOCTA, COD_AGENCIA_DEBITO, OPE_CONTA_DEBITO, NUM_CONTA_DEBITO, DIG_CONTA_DEBITO, DATA_VENCIMENTO, PRM_TOTAL, SIT_REGISTRO, TIPLANC, TIMESTAMP, OCORR_HISTORICO, CODCONV, NSAS, NSL, NSAC, CODRET, COD_USUARIO, NUM_CARTAO_CREDITO, COD_BANCO) VALUES ('000000000000000', '0000', '0000', '0000', '0000', '0000000000000', '0000', '2024-12-10', '0000000000000.00', ' ', ' ', CURRENT TIMESTAMP, 1, '0000', NULL, NULL, NULL, '0000', ' ', 0, '0000')","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [23505] [IBM][DB2] SQL0803N One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by \"GV005IP\" constrains table \"0000019053\" from having duplicate values for the index key. SQLSTATE=23505"}
{"DBCallId":"b7bef995-6557-4b01-b11d-e9478b2fbaa4","TimeStamp":"2024-12-16T14:48:08.2784605-03:00","Query":" UPDATE SEGUROS.HIST_LANC_CTA SET SIT_REGISTRO = '2' , TIMESTAMP = CURRENT_TIMESTAMP, COD_USUARIO = 'VA0469B' , CODRET = 2 WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000' AND TIPLANC = '2' AND SIT_REGISTRO = ' ' AND CODCONV = '0000'","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"e88bb448-cb27-41f3-a086-ebabb689a97b","TimeStamp":"2024-12-16T14:48:08.4364998-03:00","Query":" UPDATE SEGUROS.PARCELAS_VIDAZUL SET VLMULTA = '0000000000000.00', OCORR_HISTORICO = '0000' WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"564923ae-e1a7-49d9-a1a1-f0cf003ce71e","TimeStamp":"2024-12-16T14:48:08.5930612-03:00","Query":" SELECT SIT_REGISTRO , COD_PRODUTO FROM SEGUROS.PROPOSTAS_VA WHERE NUM_CERTIFICADO = '000000000000000'","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"3b2c1b01-f479-473c-b36e-f90fb0b42f51","TimeStamp":"2024-12-16T14:48:08.7524372-03:00","Query":" UPDATE SEGUROS.PROPOSTAS_VA SET SIT_REGISTRO = ' ', TIMESTAMP = CURRENT TIMESTAMP, DATA_MOVIMENTO = '2024-12-10', DTA_DECLINIO = '2024-12-10', COD_USUARIO = ' ' WHERE NUM_CERTIFICADO = '000000000000000'","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"dc495b7e-4b7b-4367-8f4a-f98bdf975b33","TimeStamp":"2024-12-16T14:48:08.9184327-03:00","Query":" INSERT INTO SEGUROS.HIST_CONT_PARCELVA (NUM_CERTIFICADO, NUM_PARCELA, NUM_TITULO, OCORR_HISTORICO, NUM_APOLICE, COD_SUBGRUPO, COD_FONTE, NUM_ENDOSSO, PREMIO_VG, PREMIO_AP, DATA_MOVIMENTO, SIT_REGISTRO, COD_OPERACAO, TIMESTAMP, DTFATUR) VALUES ('000000000000000', '0000', '0000000000000', '0000', '0000000000000', '0000', '0000', 0, '0000000000000.00', '0000000000000.00', '2024-12-10', '0' , '0000', CURRENT TIMESTAMP, NULL)","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [23505] [IBM][DB2] SQL0803N One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by \"I2GVT003\" constrains table \"0000069854\" from having duplicate values for the index key. SQLSTATE=23505"}
{"DBCallId":"8da78adc-32c0-4668-b9d6-aaa27bb91624","TimeStamp":"2024-12-16T14:48:09.1641121-03:00","Query":" INSERT INTO SEGUROS.RELATORIOS VALUES ( 'VA0469B' , '2024-12-10' , 'VA' , 'VA0512B' , 0, 0, '2024-12-10' , '2024-12-10' , '2024-12-10' , 0, 0, 0, 0, 0, 0, 0, 0, '0000000000000', 0, '0000', '000000000000000', 0, '0000' , 0, 0, 0, ' ' , ' ' , 0, 0, ' ' , 0, 0, ' ' , '0' , ' ' , ' ' , NULL, 0, 0, CURRENT TIMESTAMP)","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"45d31323-df8a-4f68-a698-dc3905d6b766","TimeStamp":"2024-12-16T14:48:20.7379473-03:00","Query":" SELECT VALUE(COD_OPERACAO , 0) , VALUE(DTFATUR , '0001-01-01' ) FROM SEGUROS.HIST_CONT_PARCELVA WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000' AND COD_OPERACAO BETWEEN 200 AND 299 WITH UR","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"8429cbf7-62e2-4e59-ad2f-1a20494f0235","TimeStamp":"2024-12-16T14:48:20.8953784-03:00","Query":" SELECT DAYS ('2024-12-10') - DAYS ('2024-12-10') FROM SEGUROS.SISTEMAS WHERE IDE_SISTEMA = 'VA'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"54573eaa-422c-4a27-bd8e-505f2e1983dd","TimeStamp":"2024-12-16T14:48:21.0114153-03:00","Query":" SELECT DAYS ('2024-12-10') - DAYS ('2024-12-10') FROM SEGUROS.SISTEMAS WHERE IDE_SISTEMA = 'VA'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"c7c28b0b-4277-49cc-9ba8-ebebd319e0da","TimeStamp":"2024-12-16T14:48:21.1405867-03:00","Query":" SELECT COD_FONTE ,NUM_RCAP ,VAL_RCAP ,VAL_RCAP_PRINCIPAL ,DATA_CADASTRAMENTO ,DATA_MOVIMENTO ,NUM_TITULO ,NUM_CERTIFICADO FROM SEGUROS.RCAPS WHERE NUM_CERTIFICADO = '000000000000000' AND SIT_REGISTRO = '0' AND COD_OPERACAO IN (100 ,110) FETCH FIRST 1 ROWS ONLY WITH UR","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"e245d404-a9d9-4524-9b68-03ea9e17dbfb","TimeStamp":"2024-12-16T14:48:21.2189004-03:00","Query":" SELECT COD_FONTE ,NUM_RCAP ,NUM_RCAP_COMPLEMEN ,COD_OPERACAO ,BCO_AVISO ,AGE_AVISO ,NUM_AVISO_CREDITO ,VAL_RCAP ,DATA_RCAP ,DATA_CADASTRAMENTO FROM SEGUROS.RCAP_COMPLEMENTAR WHERE NUM_RCAP = '000000000' AND COD_FONTE = '0000' AND SIT_REGISTRO = '0' AND NUM_RCAP_COMPLEMEN = 0 FETCH FIRST 1 ROWS ONLY WITH UR","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"2db61521-7e90-4fee-988b-814a9fb37740","TimeStamp":"2024-12-16T14:48:21.3016412-03:00","Query":" UPDATE SEGUROS.RCAP_COMPLEMENTAR SET SIT_REGISTRO = '1' WHERE NUM_RCAP = '000000000' AND COD_FONTE = '0000'","sqlCode":0,"rowsCount":4,"Time":"0 ms","Error":""}
{"DBCallId":"19749b01-7e77-480c-919c-d44f4d7075b4","TimeStamp":"2024-12-16T14:48:21.3860446-03:00","Query":" INSERT INTO SEGUROS.RCAP_COMPLEMENTAR (COD_FONTE , NUM_RCAP , NUM_RCAP_COMPLEMEN , COD_OPERACAO , DATA_MOVIMENTO , HORA_OPERACAO , SIT_REGISTRO , BCO_AVISO , AGE_AVISO , NUM_AVISO_CREDITO , VAL_RCAP , DATA_RCAP , DATA_CADASTRAMENTO , SIT_CONTABIL , COD_EMPRESA , TIMESTAMP) VALUES ('0000' , '000000000' , '000000000' , '0110' , '2024-12-10' , CURRENT TIME , ' ' , '0104' , '9581' , '305600001' , '0000000000009.90' , '2024-12-10' , '2024-12-10' , ' ' , '000000000' , CURRENT TIMESTAMP)","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"f126dec7-c60b-457b-8671-a60057e1ee0a","TimeStamp":"2024-12-16T14:48:21.4635281-03:00","Query":" UPDATE SEGUROS.RCAPS SET SIT_REGISTRO = '1' ,COD_OPERACAO = 210 ,NUM_APOLICE = '0000000000000' ,NUM_ENDOSSO = '000000000' ,NUM_PARCELA = '0000' WHERE NUM_RCAP = '000000000' AND COD_FONTE = '0000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"5783d783-b011-4b36-b395-9a1b7e8d14b3","TimeStamp":"2024-12-16T14:48:21.5409847-03:00","Query":" SELECT T2.NUM_CERTIFICADO FROM SEGUROS.GE_CONTROLE_CARTAO_CIELO T1 , SEGUROS.GE_RETORNO_CA_CIELO T2 , SEGUROS.PARCELAS_VIDAZUL T3 WHERE T1.NUM_CERTIFICADO = '000000000000000' AND T1.NUM_PARCELA = '0000' AND T1.COD_TP_PAGAMENTO IN ( '01' , '02' ) AND T1.NUM_PROPOSTA = T2.NUM_PROPOSTA AND T1.NUM_CERTIFICADO = T2.NUM_CERTIFICADO AND T1.NUM_PARCELA = T2.NUM_PARCELA AND T1.SEQ_CONTROL_CARTAO = T2.SEQ_CONTROL_CARTAO AND T2.COD_MOVIMENTO = '03' AND T2.COD_RETORNO = ' CC' AND T1.NUM_CERTIFICADO = T3.NUM_CERTIFICADO AND T1.NUM_PARCELA = T3.NUM_PARCELA AND T3.SIT_REGISTRO IN ( '1' , '2' ) FETCH FIRST 1 ROWS ONLY WITH UR","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"25ba350a-5736-4781-81c9-f3c328ea0971","TimeStamp":"2024-12-16T14:48:21.6600165-03:00","Query":" INSERT INTO SEGUROS.MOVTO_DEBITOCC_CEF ( COD_EMPRESA , NUM_APOLICE , NUM_ENDOSSO , NUM_PARCELA , SITUACAO_COBRANCA , DATA_VENCIMENTO , VALOR_DEBITO , DATA_MOVIMENTO , TIMESTAMP , DIA_DEBITO , COD_AGENCIA_DEB , OPER_CONTA_DEB , NUM_CONTA_DEB , DIG_CONTA_DEB , COD_CONVENIO , DATA_ENVIO , DATA_RETORNO , COD_RETORNO_CEF , NSAS , COD_USUARIO , NUM_REQUISICAO , NUM_CARTAO , SEQUENCIA , NUM_LOTE , DTCREDITO , STATUS_CARTAO , VLR_CREDITO , NUM_CERTIFICADO, COD_MOEDA , PCT_INDICE , VLR_ORIGINAL , VLR_PRORATA , VLR_JUROS , VLR_MULTA , DTA_ORIGINAL , COD_IDLG ) VALUES ( '000000000' , '0000000000000' , '000000000' , '0000' , ' ' , '2024-12-10' , '0000000000000.00', '2024-12-10' , CURRENT TIMESTAMP , '0000' , '0000' , '0000' , '0000000000000' , '0000' , '000000000' , '2024-12-10' , '2024-12-10' , '0000' , '0000' , ' ' , '0000000000000' , '0000000000000000' , '0000' , '000000000' , '2024-12-10' , ' ' , '0000000000000.00' , '000000000000000000' , '0000' , '0000.00000' , '0000000000000.00' , '0000000000000.00' , '0000000000000.00' , '0000000000000.00' , '2024-12-10' , ' ')","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [23505] [IBM][DB2] SQL0803N One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by \"I1CBT016\" constrains table \"000000A146\" from having duplicate values for the index key. SQLSTATE=23505"}
{"DBCallId":"e2756c24-1a3a-4d9c-9835-08c777a7a549","TimeStamp":"2024-12-16T14:48:21.7879826-03:00","Query":" UPDATE SEGUROS.MOVTO_DEBITOCC_CEF SET NSAS = '0000', SITUACAO_COBRANCA = '6' WHERE NUM_APOLICE = '0000000000000' AND NUM_ENDOSSO = '000000000' AND NUM_PARCELA = '0000' AND COD_CONVENIO = '000000000' AND NSAS = '0000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"21e36e3e-165a-4d71-a20a-77b9f49bed09","TimeStamp":"2024-12-16T14:48:21.9060981-03:00","Query":" UPDATE SEGUROS.HIST_LANC_CTA SET SIT_REGISTRO = '2' WHERE NUM_CERTIFICADO = '000000000000000' AND NUM_PARCELA = '0000' AND OCORR_HISTORICOCTA < '0000' AND TIPLANC = '2' AND CODCONV = 6090 AND SIT_REGISTRO = '0'","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"62d5d4b1-eb5b-40fb-be11-9587eab6abb6","TimeStamp":"2024-12-16T14:48:22.0282166-03:00","Query":" SELECT T2.NUM_CERTIFICADO , T1.VLR_TOT_PREMIO FROM SEGUROS.GE_CONTROLE_CARTAO_CIELO T1 , SEGUROS.GE_RETORNO_CA_CIELO T2 , SEGUROS.PARCELAS_VIDAZUL T3 WHERE T1.NUM_CERTIFICADO = '000000000000000' AND T1.NUM_PARCELA = '0000' AND T1.COD_TP_PAGAMENTO IN ( '01' , '02' ) AND T1.NUM_PROPOSTA = T2.NUM_PROPOSTA AND T1.NUM_CERTIFICADO = T2.NUM_CERTIFICADO AND T1.NUM_PARCELA = T2.NUM_PARCELA AND T1.SEQ_CONTROL_CARTAO = T2.SEQ_CONTROL_CARTAO AND T2.COD_MOVIMENTO = '03' AND T2.COD_RETORNO = ' CC' AND T1.NUM_CERTIFICADO = T3.NUM_CERTIFICADO AND T1.NUM_PARCELA = T3.NUM_PARCELA AND T3.SIT_REGISTRO IN ( ' ' , '0' , '1' , '2' ) FETCH FIRST 1 ROWS ONLY WITH UR","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"228b076b-ae7a-4b46-b30a-6f6b8e700818","TimeStamp":"2024-12-16T14:48:22.1421007-03:00","Query":" UPDATE SEGUROS.MOVTO_DEBITOCC_CEF SET COD_AGENCIA_DEB = '0000', OPER_CONTA_DEB = '0000' , NUM_CONTA_DEB = '0000000000000' , DIG_CONTA_DEB = '0000' , DIA_DEBITO = '0000' , DATA_MOVIMENTO = '2024-12-10' , SITUACAO_COBRANCA = ' ', TIMESTAMP = CURRENT_TIMESTAMP WHERE NUM_CARTAO = '0000000000000000' AND NUM_APOLICE = '0000000000000' AND NUM_PARCELA = '0000' AND SITUACAO_COBRANCA = 'R'","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"544d1437-a31d-4886-8cc5-f510a7944d18","TimeStamp":"2024-12-16T14:48:22.2656535-03:00","Query":" SELECT COUNT(*) FROM SEGUROS.MOVTO_DEBITOCC_CEF WHERE NUM_CARTAO = '0000000000000000' AND NUM_PARCELA = '0000' AND COD_CONVENIO = '000000000' AND SITUACAO_COBRANCA IN ( ' ' , '0' , '1' , '2' , '5' )","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"a1121052-1b6b-4c5d-89c4-cdf381d65ae7","TimeStamp":"2024-12-16T14:48:22.3991165-03:00","Query":" UPDATE SEGUROS.AVISOS_SALDOS SET SALDO_ATUAL = (SALDO_ATUAL - '0000000000009.90') WHERE BCO_AVISO = '0104' AND AGE_AVISO = '9581' AND NUM_AVISO_CREDITO = '305600001'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}