{"DBCallId":"8badea1b-f889-4bc0-b1a1-e6e1cd7cb3ec","TimeStamp":"2025-02-14T14:28:44.915168-03:00","Query":" INSERT INTO SEGUROS.GE_AR_DETALHE (NOM_ARQUIVO, SEQ_GERACAO, DTH_ANO_REFERENCIA, DTH_MES_REFERENCIA, DTH_MOVIMENTO, DTH_GERACAO, DTH_RECEPCAO, IND_MEIO_ENVIO, STA_ENVIO_RECEPCAO, COD_TIPO_ARQUIVO, QTD_REG_PROCESSADO, QTD_REG_REJEITADOS, QTD_REG_ACEITOS, DTH_TIMESTAMP) VALUES (' ', '000000000', '0000', '0000', '2023-02-02', '2023-02-02', '2023-02-02', ' ', ' ', ' ', '000000000', '000000000', '000000000', CURRENT TIMESTAMP)","sqlCode":999,"rowsCount":0,"Time":"11 ms","Error":">>> Erro: ERROR [23503] [IBM][DB2] SQL0530N The insert or update value of the FOREIGN KEY \"GE233FK1\" is not equal to any value of the parent key of the parent table."}
{"DBCallId":"0d71258c-93d2-4058-b285-57e221877465","TimeStamp":"2025-02-14T14:29:49.3598985-03:00","Query":" INSERT INTO SEGUROS.VG_FOLLOW_UP (NOM_ARQUIVO, SEQ_GERACAO, NUM_FITA_CEF, NUM_NOSSA_FITA, NUM_LANCAMENTO, COD_CONVENIO, NUM_CERTIFICADO, COD_BANCO, STA_PROCESSAMENTO, NUM_VERSAO_LAYOUT, REG_LANCAMENTO, COD_USUARIO, DTH_ATUALIZACAO) VALUES (' ', '000000000', '000000000', '000000000', '000000000', '000000000', '000000000000000', '0000', ' ', '0000', ' ', ' ', CURRENT TIMESTAMP)","sqlCode":999,"rowsCount":0,"Time":"3 ms","Error":">>> Erro: ERROR [23513] [IBM][DB2] SQL0545N The requested operation is not allowed because a row does not satisfy the check constraint \"VGT073_CHK\"."}
{"DBCallId":"0a944b55-06cd-41dc-ad8e-66bb6b63e899","TimeStamp":"2025-02-14T14:29:53.4395308-03:00","Query":" INSERT INTO SEGUROS.VG_FOLLOW_UP (NOM_ARQUIVO, SEQ_GERACAO, NUM_FITA_CEF, NUM_NOSSA_FITA, NUM_LANCAMENTO, COD_CONVENIO, NUM_CERTIFICADO, COD_BANCO, STA_PROCESSAMENTO, NUM_VERSAO_LAYOUT, REG_LANCAMENTO, COD_USUARIO, DTH_ATUALIZACAO) VALUES (' ', '000000000', '000000000', '000000000', '000000000', '000000000', '000000000000000', '0000', ' ', '0000', ' ', ' ', CURRENT TIMESTAMP)","sqlCode":999,"rowsCount":0,"Time":"3 ms","Error":">>> Erro: ERROR [23513] [IBM][DB2] SQL0545N The requested operation is not allowed because a row does not satisfy the check constraint \"VGT073_CHK\"."}
{"DBCallId":"ee44a63d-2840-4ac9-9f14-e4d0dfad8717","TimeStamp":"2025-02-14T14:29:57.5234759-03:00","Query":" SELECT DTMOVABE FROM SEGUROS.V1SISTEMA WHERE IDSISTEM = 'VA' WITH UR","sqlCode":0,"rowsCount":1,"Time":"3 ms","Error":""}
{"DBCallId":"0d97d8ae-170b-4a4d-a2fc-a097abd1ab76","TimeStamp":"2025-02-14T14:29:58.5551127-03:00","Query":" SELECT DTH_ANO_REFERENCIA , DTH_MES_REFERENCIA FROM SEGUROS.GE_AR_DETALHE WHERE NOM_ARQUIVO = ' ' AND SEQ_GERACAO = '000000000'","sqlCode":0,"rowsCount":0,"Time":"6 ms","Error":""}
{"DBCallId":"4bc3d194-5386-4bc7-9587-72abc8bc053a","TimeStamp":"2025-02-14T14:29:59.2084336-03:00","Query":" SELECT MAX(SEQ_GERACAO) FROM SEGUROS.GE_AR_DETALHE WHERE NOM_ARQUIVO = ' '","sqlCode":0,"rowsCount":1,"Time":"3 ms","Error":""}
{"DBCallId":"6b128483-1ae1-4993-b865-e10f7723a8a6","TimeStamp":"2025-02-14T14:30:00.4425234-03:00","Query":" INSERT INTO SEGUROS.GE_AR_DETALHE (NOM_ARQUIVO, SEQ_GERACAO, DTH_ANO_REFERENCIA, DTH_MES_REFERENCIA, DTH_MOVIMENTO, DTH_GERACAO, DTH_RECEPCAO, IND_MEIO_ENVIO, STA_ENVIO_RECEPCAO, COD_TIPO_ARQUIVO, QTD_REG_PROCESSADO, QTD_REG_REJEITADOS, QTD_REG_ACEITOS, DTH_TIMESTAMP) VALUES (' ', '000000000', '0000', '0000', '2023-02-02', '2023-02-02', '2023-02-02', ' ', ' ', ' ', '000000000', '000000000', '000000000', CURRENT TIMESTAMP)","sqlCode":999,"rowsCount":0,"Time":"3 ms","Error":">>> Erro: ERROR [23503] [IBM][DB2] SQL0530N The insert or update value of the FOREIGN KEY \"GE233FK1\" is not equal to any value of the parent key of the parent table."}