{"DBCallId":"88075419-f89e-4285-b244-9c082ff6858e","TimeStamp":"2024-12-16T14:42:33.9183679-03:00","Query":" SELECT DTMOVABE FROM SEGUROS.V1SISTEMA WHERE IDSISTEM = 'VG'","sqlCode":0,"rowsCount":1,"Time":"90 ms","Error":""}
{"DBCallId":"14a6f787-7f94-48bb-a76f-2d775d1c724f","TimeStamp":"2024-12-16T14:42:37.2144398-03:00","Query":" SELECT RAMO_VG , RAMO_AP , NUM_RAMO_PRSTMISTA FROM SEGUROS.V1PARAMRAMO","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"b639a961-b478-4872-bf58-83cf830f4b31","TimeStamp":"2024-12-16T14:42:44.8578047-03:00","Query":" SELECT CODUNIMO , VLCRUZAD FROM SEGUROS.V1MOEDA WHERE TIPO_MOEDA = '0' AND SITUACAO = '0'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"e71edf69-e1a3-4955-ad93-fac2cf944fc2","TimeStamp":"2024-12-16T14:42:49.1612694-03:00","Query":"SELECT A.NUM_APOLICE , A.COD_SUBGRUPO , A.COD_FONTE , A.NUM_PROPOSTA , A.TIPO_SEGURADO , A.NUM_CERTIFICADO , A.DAC_CERTIFICADO , A.TIPO_INCLUSAO , A.COD_CLIENTE , A.COD_AGENCIADOR , A.COD_CORRETOR , A.COD_PLANOVGAP , A.COD_PLANOAP , A.FAIXA , A.AUTOR_AUM_AUTOMAT , A.TIPO_BENEFICIARIO , A.PERI_PAGAMENTO , A.PERI_RENOVACAO , A.COD_OCUPACAO , A.ESTADO_CIVIL , A.IDE_SEXO , A.COD_PROFISSAO , A.NATURALIDADE , A.OCORR_ENDERECO , A.OCORR_END_COBRAN , A.BCO_COBRANCA , A.AGE_COBRANCA , A.DAC_COBRANCA , A.NUM_MATRICULA , A.NUM_CTA_CORRENTE , A.DAC_CTA_CORRENTE , A.VAL_SALARIO , A.TIPO_SALARIO , A.TIPO_PLANO , A.PCT_CONJUGE_VG , A.PCT_CONJUGE_AP , A.QTD_SAL_MORNATU , A.QTD_SAL_MORACID , A.QTD_SAL_INVPERM , A.TAXA_AP_MORACID , A.TAXA_AP_INVPERM , A.TAXA_AP_AMDS , A.TAXA_AP_DH , A.TAXA_AP_DIT , A.TAXA_VG , A.IMP_MORNATU_ANT , A.IMP_MORNATU_ATU , A.IMP_MORACID_ANT , A.IMP_MORACID_ATU , A.IMP_INVPERM_ANT , A.IMP_INVPERM_ATU , A.IMP_AMDS_ANT , A.IMP_AMDS_ATU , A.IMP_DH_ANT , A.IMP_DH_ATU , A.IMP_DIT_ANT , A.IMP_DIT_ATU , A.PRM_VG_ANT , A.PRM_VG_ATU , A.PRM_AP_ANT , A.PRM_AP_ATU , A.COD_OPERACAO , A.DATA_OPERACAO , A.COD_SUBGRUPO_TRANS , A.SIT_REGISTRO , A.COD_USUARIO , A.DATA_AVERBACAO , A.DATA_ADMISSAO , A.DATA_INCLUSAO , A.DATA_NASCIMENTO , A.DATA_FATURA , A.DATA_REFERENCIA , A.DATA_MOVIMENTO , A.DATA_MOVIMENTO - 1 DAY , A.COD_EMPRESA , B.RAMO , B.MODALIDA FROM SEGUROS.V1MOVIMENTO A , SEGUROS.V0APOLICE B WHERE A.DATA_AVERBACAO IS NOT NULL AND A.DATA_INCLUSAO IS NULL AND A.COD_OPERACAO >= 0500 AND A.COD_OPERACAO <= 0599 AND A.NUM_APOLICE = B.NUM_APOLICE AND A.DATA_OPERACAO > '2015-06-01'","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [58005] [IBM][DB2.NET] SQL0902 An unexpected exception has occurred in Process: 13156 Thread 24 AppDomain: Name:testhost There are no context policies. Function: DB2DataReader.Read() CallStack: at System.Environment.get_StackTrace() at IBM.Data.Db2.DB2ConnPool.HandleUnknownErrors(String strFncMsg, Exception exception, Boolean bThrow) at IBM.Data.Db2.DB2DataReader.Read() at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1201 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 815 at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 737 at IA_ConverterCommons.QueryBasis`1.Open(Object procParams) in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\IA_ConverterCommons\\Basis\\QueryBasis.cs:line 234 at Sias.VidaEmGrupo.DB2.VG0040B.VG0040B_TMOVIMENTO.Open() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaEmGrupo\\DB2\\VG0040B\\VG0040B_TMOVIMENTO.cs:line 119 at Code.VG0040B.M_090_000_CURSOR_V1MOVIMENTO_DB_OPEN_1() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\Sias.VidaEmGrupo\\Code\\VG0040B.cs:line 984 at FileTests.Test_DB.VG0040B_Tests_DB.VG0040B_Database() in E:\\PROJETOS\\FOURSYS\\SIAS\\SIAS-Batch\\FileTests.Test\\FileTests.Test\\VG0040B_Tests_DB.cs:line 27 at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 151 at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 278 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__1() at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<InvokeTestMethodAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 243 at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 242 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestInvoker.cs:line 112 at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 207 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestInvoker`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 190 at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 84 at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 67 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) at Xunit.Sdk.TestRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestRunner`1.RunAsync() at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCaseRunner.cs:line 139 at Xunit.Sdk.TestCaseRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCaseRunner.cs:line 82 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCaseRunner`1.RunAsync() at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs:line 162 at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestMethodRunner.cs:line 45 at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 136 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() at Xunit.Sdk.TestMethodRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 106 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestMethodRunner`1.RunAsync() at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestClassRunner.cs:line 199 at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() at Xunit.Sdk.TestClassRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs:line 175 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestClassRunner`1.RunAsync() at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs:line 185 at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() at Xunit.Sdk.TestCollectionRunner`1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs:line 101 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Xunit.Sdk.TestCollectionRunner`1.RunAsync() at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(IMessageBus messageBus, ITestCollection testCollection, IEnumerable`1 testCases, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs:line 262 at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs:line 211 at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) at System.Threading.Tasks.Task.ExecuteEntry() at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s) at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 106 at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action) in /_/src/xunit.execution/Sdk/Utility/ExecutionContextHelper.cs:line 110 at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 96 at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in /_/src/common/XunitWorkerThread.cs:line 37 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) InnerException Message: len ('-4187064') must be a non-negative value. (Parameter 'len') Actual value was -4187064. Check InnerException property for more detail. SQLSTATE=58005"}
{"DBCallId":"81cdd6a1-a0c8-42cf-88bd-b595c985fe89","TimeStamp":"2024-12-16T14:42:57.3109916-03:00","Query":"SELECT NRPARCEL FROM SEGUROS.V0PARCELVA WHERE NRCERTIF = '000000000000000' ORDER BY NRPARCEL DESC","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"f7115bc7-34c6-42db-b94c-bbeee8764569","TimeStamp":"2024-12-16T14:43:28.4734422-03:00","Query":" SELECT OCORR_HISTORICO , NUM_ITEM , DATA_INIVIGENCIA + 1 YEAR - 1 DAY , DATA_ADMISSAO , SIT_REGISTRO FROM SEGUROS.V1SEGURAVG WHERE NUM_CERTIFICADO = '000000000000000' AND TIPO_SEGURADO = ' '","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ExecuteReader requires an open connection. The connection's current state is Closed."}
{"DBCallId":"5804b355-ea91-4ca5-bd69-843ae5ac96fc","TimeStamp":"2024-12-16T14:43:37.0441043-03:00","Query":" SELECT VALUE(COUNT(*) ,0) FROM SEGUROS.V0MOVIMENTO WHERE NUM_CERTIFICADO = '000000000000000' AND COD_OPERACAO NOT BETWEEN 0500 AND 599 AND DATA_MOVIMENTO < '2024-12-10' AND DATA_INCLUSAO IS NULL","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"6e014bc5-1739-4aff-996c-c47eac99577f","TimeStamp":"2024-12-16T14:43:37.8201016-03:00","Query":" SELECT MAX(DTTERVIG) FROM SEGUROS.V0COBERPROPVA WHERE NRCERTIF = '000000000000000'","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"e6af9e72-0f4a-41c9-b294-5445bafe8625","TimeStamp":"2024-12-16T14:43:38.5072374-03:00","Query":" INSERT INTO SEGUROS.V0COBERAPOL VALUES ('0000000000000', '000000000', '000000000', '0000', '0000', '0000', '0000', '0000000000000.00', '0000000000.00000', '0000000000000.00', '0000000000.00000', '000.00', '0000', '2024-12-10', '2024-12-10', '000000000', CURRENT TIMESTAMP, ' ')","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [23505] [IBM][DB2] SQL0803N One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by \"IPGET034\" constrains table \"0000008454\" from having duplicate values for the index key. SQLSTATE=23505"}
{"DBCallId":"05242da7-1e3b-4832-8975-1efe4f991bf9","TimeStamp":"2024-12-16T14:43:39.1363976-03:00","Query":" INSERT INTO SEGUROS.V0HISTSEGVG VALUES ('0000000000000', '0000', '000000000', '0000', '2024-12-10', '00:00:00', '2024-12-10', '0000', '0000', '2024-12-10', ' ', '000000000', '0001', '0000')","sqlCode":999,"rowsCount":0,"Time":"0 ms","Error":">>> Erro: ERROR [23505] [IBM][DB2] SQL0803N One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by \"I1GVT013\" constrains table \"000FFEE44E\" from having duplicate values for the index key. SQLSTATE=23505"}
{"DBCallId":"6f61b7bf-342e-4371-9a26-5c8d9691ba04","TimeStamp":"2024-12-16T14:43:39.8152504-03:00","Query":" UPDATE SEGUROS.V0SEGURAVG SET SIT_REGISTRO = '0' , DATA_ADMISSAO = '2024-12-10', OCORR_HISTORICO = '0000', COD_PROFISSAO = 9999 WHERE NUM_CERTIFICADO = '000000000000000' AND TIPO_SEGURADO = ' ' AND SIT_REGISTRO IN ( '2' , '9' )","sqlCode":0,"rowsCount":0,"Time":"0 ms","Error":""}
{"DBCallId":"9ea68a3f-15f9-49fb-86aa-f4e58733029d","TimeStamp":"2024-12-16T14:43:40.5189299-03:00","Query":" UPDATE SEGUROS.V0MOVIMENTO SET DATA_INCLUSAO = '2024-12-10', DATA_REFERENCIA = '2024-12-10' WHERE COD_FONTE = '0000' AND NUM_PROPOSTA = '000000000' AND TIPO_SEGURADO = ' '","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"1a24ceed-723d-4ce4-9cad-7e8600c844ef","TimeStamp":"2024-12-16T14:43:42.1449125-03:00","Query":" SELECT NUM_APOLICE FROM SEGUROS.V0RELATORIOS WHERE CODRELAT IN ( 'VP0198B' , 'VP0199B' ) AND NRCERTIF = '000000000000000'","sqlCode":0,"rowsCount":4,"Time":"0 ms","Error":""}
{"DBCallId":"5f6f4508-ad00-4260-939f-e00443dd44c7","TimeStamp":"2024-12-16T14:43:54.624453-03:00","Query":" INSERT INTO SEGUROS.V0RELATORIOS VALUES ( 'VG0040B' , '2024-12-10', 'VP' , 'VP0198B' , 0, 0, CURRENT DATE, CURRENT DATE, CURRENT DATE, 0, 0, 0, 0, 0, 0, 0, 0, '0000000000000', 0, 0, '000000000000000', 0, '0000', '0000', 0, 0, ' ' , ' ' , 0, 0, ' ' , 0, 0, ' ' , ' ' , ' ' , ' ' , NULL, 0, NULL, CURRENT TIMESTAMP)","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"064e278c-c447-4496-b199-4949030dd2a8","TimeStamp":"2024-12-16T14:43:55.2879505-03:00","Query":" INSERT INTO SEGUROS.V0RELATORIOS VALUES ( 'VG0040B' , '2024-12-10', 'VP' , 'VP0199B' , 0, 0, CURRENT DATE, CURRENT DATE, CURRENT DATE, 0, 0, 0, 0, 0, 0, 0, 0, '0000000000000', 0, 0, '000000000000000', 0, '0000', '0000', 0, 0, ' ' , ' ' , 0, 0, ' ' , 0, 0, ' ' , ' ' , ' ' , ' ' , NULL, 0, NULL, CURRENT TIMESTAMP)","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}
{"DBCallId":"2bd09563-ffae-46ec-99ff-9605d9bb5485","TimeStamp":"2024-12-16T14:43:55.8001589-03:00","Query":" UPDATE SEGUROS.V0PROPOSTAVA SET SITUACAO = '3' , NRPRIPARATZ = 0, QTDPARATZ = 0, CODOPER = '0000', DTMOVTO = '2024-12-10', CODUSU = ' ', NRPROPOS = '000000000', TIMESTAMP = CURRENT TIMESTAMP WHERE NRCERTIF = '000000000000000'","sqlCode":0,"rowsCount":0,"Time":"3 ms","Error":""}
{"DBCallId":"ac028007-0772-4876-88a8-08ff3b386f6b","TimeStamp":"2024-12-16T14:43:56.3075767-03:00","Query":" UPDATE SEGUROS.V0SEGURAVG SET NUM_CARNE = '0000' WHERE NUM_CERTIFICADO = '000000000000000' AND TIPO_SEGURADO = ' '","sqlCode":0,"rowsCount":1,"Time":"0 ms","Error":""}